import { ensureFile, walk } from "jsr:@std/fs";
import { join, relative, resolve } from "jsr:@std/path";
import { ensure, is } from "jsr:@core/unknownutil";

const __dirname = ensure(import.meta.dirname, is.String);

type Test = {
  number: number;
  name: string;
  path: string;
};

async function getTests(path: string): Promise<Test[]> {
  const tests: Test[] = [];
  for await (const entry of walk(path)) {
    if (!entry.isFile) {
      continue;
    }
    const { name, path } = entry;
    const match = ensure(name.match(/^(\d+)_(.*)\.lico$/), is.Array);
    const number = ensure(parseInt(ensure(match[1], is.String)), is.Number);
    const testName = ensure(match[2], is.String);
    const relativePath = relative(
      resolve(__dirname, "..", "tests"),
      path,
    );
    tests.push({ number, name: testName, path: relativePath });
  }
  tests.sort((a, b) => a.number - b.number);
  return tests;
}

async function writeFile(path: string, content: string): Promise<void> {
  await ensureFile(path);
  await Deno.writeTextFile(path, content.trim() + "\n");
}

await writeFile(
  resolve(__dirname, "..", "tests", "ok.rs"),
  `
//! Generated by "../test_data/gen.ts". Do not edit by hand.
#![cfg_attr(rustfmt, rustfmt_skip)]
use foundation::syntax::SyntaxNode;
use insta::{assert_snapshot, with_settings};
macro_rules! test {
    ($name:ident, $path:literal) => {
        #[test]
        fn $name() {
            let source = std::include_str!($path);
            let (green, err) = parser::parse(source, lexer::tokenize(source));
            assert!(err.is_empty(), "{:?}", err);
            with_settings!({
                prepend_module_to_snapshot => false,
                omit_expression => true,
                description => stringify!($name),
            }, {
                assert_snapshot!(format!("{:#?}", SyntaxNode::new_root(green)));
            });
        }
    };
}
${
    (await getTests(join(__dirname, "ok"))).map((test) => {
      const number = test.number.toString().padStart(3, "0");
      return `test!(ok_${number}_${test.name}, "${test.path}");`;
    })
      .join("\n")
  }
`,
);
